apiVersion: v1
kind: Secret
metadata:
  name: credpay-db
  namespace: credpay
  labels:
    app.kubernetes.io/part-of: credpay
type: Opaque
StringData:
  DB_password: "replace_me"
  SPRING_DATASOURCE_PASSWORD: "replace_me"